### ISSUE TITLE
Strapi 4?

### ISSUE THREAD

**Issue by SoftCreatR** [alexkainzinger/strapi-middleware-upload-plugin-cache#2]
Hi,

are there any plans to support Strapi 4?

https://github.com/strapi/strapi/issues/12657

**Comment by alexkainzinger** [comment]
Finally managed to add support to it. 

I have seen your issue https://github.com/strapi/strapi/issues/12657, I guess your problem has been resolved by now

**Comment by SoftCreatR** [comment]
Yeah, i found a way for my case, but thank you :)
