### ISSUE TITLE
Configuration does not work, it is always enabled by default and cannot change maxAge

### ISSUE THREAD

**Issue by nd90364** [alexkainzinger/strapi-middleware-upload-plugin-cache#4]
I am using version 1.1.1 (for Strapi v3) and I have created a config/plugin.js file, but it ignores all of the settings.  It is always enabled even if I set enabled: false.  It also always has the max age of [maxAge=86400000]

Steps to reproduce:
1.) create Strapi v3 project
2.) install version 1.1.1 of plugin
3.) touch config/plugin.js
4.) set enabled: false or change max age to something other than 86400000

**Comment by alexkainzinger** [comment]
correct, for some reason I copied to wrong README to the docs/v3 folder when I restructured the project for Strapi 4.

the correct documentation can be found here https://github.com/alexkainzinger/strapi-middleware-upload-plugin-cache/blob/1.1.1/README.md
